### PR TITLE
1.9.14 > 1.9.15

### PR DESCRIPTION
**Pull request by gfanton**
-Fix some bugs.
-Now compatible on 1.6 ~ 1.6.1.0

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @gfanton,

Some fixes to apply. When I reach the carrier step in the checkout process, I get the following popup:
capture du 2015-07-27 15 49 34

But if I don't cant to write my phone number, I cannot close the windows with the button "Fermer" ! And if I write it, I cannot choose a pickup point because nothing appear ...

When you insert the Google Maps API, you must use THIS url:
```
https://maps.google.com/maps/api/js?sensor=false
```

**Comment by gfanton** [comment]
Hello,
I fix those issues, thanks for reporting.

**Comment by Quetzacoalt91** [comment]
Hoy,

The issue with the phone number still occurs (create a new customer on the shop to reproduce):
capture du 2015-07-29 15 59 51

I also found another issue to fix:
capture du 2015-07-29 15 48 38
When I displey the pickup point details, I cannot select anymore another option. :/

**Comment by Quetzacoalt91** [comment]
Hoy,

One last thing, still related to this "Close" button:
capture du 2015-07-31 10 24 51

Here again, if the customer does not want to use TNT, he should not have to choose a pickup point.

Thanks

**Comment by gfanton** [comment]
I was aware of this, i agree it's much better. But the fact is if the user can close the popup without a selected `Relais Colis` it can be a pain for the merchant (a user can take the `Relais Colis` carrier, but don't have selected any `Relais Colis`). I can unselect the carrier, but even in this case the user can pass the step without a carrier.
Another solution for me in this case is if no result is shown (Error) disable the close boutton then show a message that explicitly say "Sorry but no `Relais Colis` can be found for your location, please choose an other/*valid* location before closing this popup" or something like that.

**Comment by Quetzacoalt91** [comment]
In this case (Pickup point not selected), we could prevent the click on the button "Checkout" if the selected carrier is "TNT Pickup point" and they is no place selected.

Instead of this behaviour, the customer stays on the carrier list and get the popup back ! The behavior here would be : "Okay, you can close the popup if you want to, but do not even try to go to the next step without selecting any point". :)

**Comment by gfanton** [comment]
Ok, now the close button will ALWAYS close the popup, if the user didn't put his phone number or didn't select a Pickup point (pickup case only) the selected carrier will be uncheck and the Process Carrier button will be disabled until the user select a new carrier again.

**Comment by Quetzacoalt91** [comment]
Hi @gfanton,

This is better now, thanks. Your PR has just been merged and the changes will be available from tomorrow.

Best regards

**Pull request merged**
